version: '3.8'

volumes:
  prometh0_data:
    driver: local
    driver_opts:
      type: none
      device: /data/prometheus0
      o: bind

  prometh1_data:
    driver: local
    driver_opts:
      type: none
      device: /data/prometheus1
      o: bind

  prometh2_data:
    driver: local
    driver_opts:
      type: none
      device: /data/prometheus2
      o: bind

  sidecar0_data:
    driver: local
    driver_opts:
      type: none
      device: /data/sidecar0
      o: bind

  sidecar1_data:
    driver: local
    driver_opts:
      type: none
      device: /data/sidecar1
      o: bind

  sidecar2_data:
    driver: local
    driver_opts:
      type: none
      device: /data/sidecar2
      o: bind

  grafana_data:
    driver: local
    driver_opts:
      type: none
      device: /data/grafana
      o: bind

networks:
  monitor-net:
    driver: bridge

services:
  prometheus0:
    user: "993:988"
    image: prom/prometheus:v2.22.1
    volumes:
      - ./prometheus0/:/etc/prometheus/
      - prometh0_data:/data/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.listen-address=0.0.0.0:9090'
    ports:
      - 9090:9090
    networks:
      - monitor-net
    restart: always
    
  prometheus1:
    user: "993:988"
    image: prom/prometheus:v2.22.1
    volumes:
      - ./prometheus1/:/etc/prometheus/
      - prometh1_data:/data/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.listen-address=0.0.0.0:9090'
    ports:
      - 9091:9090
    networks:
      - monitor-net
    restart: always

  prometheus2:
    user: "993:988"
    image: prom/prometheus:v2.22.1
    volumes:
      - ./prometheus2/:/etc/prometheus/
      - prometh2_data:/data/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.listen-address=0.0.0.0:9090'
    ports:
      - 9092:9090
    networks:
      - monitor-net
    restart: always

  sidecar0:
      image: thanosio/thanos:v0.16.0
      # container_name: thanos-sidecar0
      command:
        - "sidecar"
        - "--debug.name=sidecar-0"
        - "--log.level=debug"
        - "--grpc-address=0.0.0.0:10900"
        - "--grpc-grace-period=1s"
        - "--http-address=0.0.0.0:10910"
        - "--http-grace-period=1s"
        - "--prometheus.url=http://prometheus0:9090"
        - "--tsdb.path=/data/prometheus"
        # - "--objstore.config-file=/bucket.yml"
      volumes:
        - sidecar0_data:/data/sidecar
        # - ./thanos/sidecar/bucket.yml:/etc/thanos/bucket.yml
      depends_on:
        # - minio
        - prometheus0
      networks:
        - monitor-net

  sidecar1:
      image: thanosio/thanos:v0.16.0
      # container_name: thanos-sidecar0
      command:
        - "sidecar"
        - "--debug.name=sidecar-1"
        - "--log.level=debug"
        - "--grpc-address=0.0.0.0:10901"
        - "--grpc-grace-period=1s"
        - "--http-address=0.0.0.0:10911"
        - "--http-grace-period=1s"
        - "--prometheus.url=http://prometheus1:9090"
        - "--tsdb.path=/data/prometheus"
        # - "--objstore.config-file=/bucket.yml"
      volumes:
        - sidecar1_data:/data/sidecar
        # - ./thanos/sidecar/bucket.yml:/etc/thanos/bucket.yml
      depends_on:
        # - minio
        - prometheus1
      networks:
        - monitor-net

  sidecar2:
      image: thanosio/thanos:v0.16.0
      # container_name: thanos-sidecar0
      command:
        - "sidecar"
        - "--debug.name=sidecar-2"
        - "--log.level=debug"
        - "--grpc-address=0.0.0.0:10902"
        - "--grpc-grace-period=1s"
        - "--http-address=0.0.0.0:10912"
        - "--http-grace-period=1s"
        - "--prometheus.url=http://prometheus2:9090"
        - "--tsdb.path=/data/prometheus"
        # - "--objstore.config-file=/bucket.yml"
      volumes:
        - sidecar2_data:/data/sidecar
        # - ./thanos/sidecar/bucket.yml:/etc/thanos/bucket.yml
      depends_on:
        # - minio
        - prometheus2
      networks:
        - monitor-net

  query0:
    image: thanosio/thanos:v0.16.0
    # container_name: thanos-query0
    command:
      - "query"
      - "--debug.name=query-0"
      - "--log.level=debug"
      - "--grpc-address=0.0.0.0:10920"
      - "--grpc-grace-period=1s"
      - "--http-address=0.0.0.0:10930"
      - "--http-grace-period=1s"
      - "--query.replica-label=replica"
      - "--query.partial-response"
      - "--store=sidecar0:10900"
      - "--store=sidecar1:10901"
      - "--store=sidecar2:10902"
      # - "--store=store:10905"
      # - "--store=receive:10907"
    ports:
      - 10930:10930
    depends_on:
      # - minio
      - sidecar0
      - sidecar1
      - sidecar2
      # - store
      # - receive
    networks:
      - monitor-net

  query1:
    image: thanosio/thanos:v0.16.0
    # container_name: thanos-query0
    command:
      - "query"
      - "--debug.name=query-1"
      - "--log.level=debug"
      - "--grpc-address=0.0.0.0:10921"
      - "--grpc-grace-period=1s"
      - "--http-address=0.0.0.0:10931"
      - "--http-grace-period=1s"
      - "--query.replica-label=replica"
      - "--query.partial-response"
      - "--store=sidecar0:10900"
      - "--store=sidecar1:10901"
      - "--store=sidecar2:10902"
      # - "--store=store:10905"
      # - "--store=receive:10907"
    ports:
      - 10931:10931
    depends_on:
      # - minio
      - sidecar0
      - sidecar1
      - sidecar2
      # - store
      # - receive
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:7.3.2
    user: "472:0"
    depends_on:
      - prometheus0
      - prometheus1
      - prometheus2
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/home.json:/usr/share/grafana/public/dashboards/home.json
    env_file:
      - ./grafana/config.monitoring
    networks:
      - monitor-net
    restart: always


