version: '3.8'

volumes:
  prometh0_data:
    driver: local
    driver_opts:
      type: none
      device: /data/prometheus0
      o: bind

  prometh1_data:
    driver: local
    driver_opts:
      type: none
      device: /data/prometheus1
      o: bind

  prometh2_data:
    driver: local
    driver_opts:
      type: none
      device: /data/prometheus2
      o: bind

  grafana_data:
    driver: local
    driver_opts:
      type: none
      device: /data/grafana
      o: bind

networks:
  monitor-net:
    driver: bridge

services:
  prometheus0:
    user: "993:988"
    image: prom/prometheus:v2.22.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometh0_data:/data/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - monitor-net
    restart: always
    
  prometheus1:
    user: "993:988"
    image: prom/prometheus:v2.22.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometh1_data:/data/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - monitor-net
    restart: always

  prometheus2:
    user: "993:988"
    image: prom/prometheus:v2.22.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometh2_data:/data/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - monitor-net
    restart: always

  grafana:
    image: grafana/grafana:7.3.2
    user: "472:0"
    depends_on:
      - prometheus0
      - prometheus1
      - prometheus2
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/home.json:/usr/share/grafana/public/dashboards/home.json
    env_file:
      - ./grafana/config.monitoring
    networks:
      - monitor-net
    restart: always


